import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {rolldown} from 'rolldown';

const read=async p=>JSON.parse(await fs.readFile(p,'utf8'));
const audit=await read('local-data/setup1-audit/audit.json');
const counter=await read('local-data/setup1-audit/counterfactual.json');
const ignore=await read('local-data/setup1-audit/no-ignore.json');
const reference=process.argv[2] ?? 'C:/Users/Philip/.codex/worktrees/97f8/trading-monitor/.debug/wave1-september';
const rebuilt=process.argv[3] ?? '.debug/wave2-rebuild-september';
await fs.mkdir('.debug',{recursive:true});
await fs.writeFile('.debug/audit-helpers.mjs',"export {groupSetupSnapshots} from '../src/tradeSetup2Review.js';export {savedDealingRangePriceOutcome} from '../src/savedDealingRangePriceOutcome.js';");
const bundle=await rolldown({input:path.resolve('.debug/audit-helpers.mjs'),platform:'node'});
await bundle.write({file:'.debug/audit-helpers-bundle.mjs',format:'esm'});await bundle.close();
const {groupSetupSnapshots,savedDealingRangePriceOutcome}=await import(pathToFileURL(path.resolve('.debug/audit-helpers-bundle.mjs')));
const date=v=>v==null?'—':new Intl.DateTimeFormat('de-DE',{timeZone:'Europe/Berlin',dateStyle:'short',timeStyle:'medium'}).format(new Date(typeof v==='number'?v*1000:v));
const escape=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const table=(head,rows)=>`<table><tr>${head.map(x=>`<th>${escape(x)}</th>`).join('')}</tr>${rows.map(r=>`<tr>${r.map(x=>`<td>${escape(x)}</td>`).join('')}</tr>`).join('')}</table>`;
const pretty=v=>JSON.stringify(v);
async function run(dir){const meta=await read(dir+'/run.json'),setups=await read(dir+'/GBPUSD-setups.json'),entries=await read(dir+'/GBPUSD-entries.json');
  if(meta.status!=='complete')throw new Error(`Run incomplete: ${dir}`);
  const groups=groupSetupSnapshots([...setups,...entries.map(x=>x.snapshot)]),valid=groups.filter(g=>g.firstValidated);
  const statuses={},outcomes={};for(const g of groups){const s=g.snapshot.dealingRange.status;statuses[s]=(statuses[s]??0)+1;}for(const g of valid){const s=savedDealingRangePriceOutcome(g).status;outcomes[s]=(outcomes[s]??0)+1;}
  return {meta,groups,entries,metrics:{runId:meta.id,setups:(await read(dir+'/GBPUSD-sources.json')).length,drs:groups.length,validated:valid.length,
    confirmedEver:groups.filter(g=>g.firstValidated||[g.candidate,g.latestCandidate,...g.entries].some(s=>s?.dealingRange?.status==='confirmed')).length,
    statuses,outcomes,entries:entries.length,wallMs:meta.provenance.measurement?.wallMs}};
}
const runs=[await run(reference),await run(rebuilt)];
await fs.writeFile('local-data/setup1-audit/september-comparison.json',JSON.stringify(runs.map(r=>r.metrics),null,2));
const entryRows=r=>r.entries.map(e=>[e.snapshot.setupKey,date(e.snapshot.entry.recognizedAt),e.snapshot.entry.price,...e.outcomes.map(o=>`${o.variant}: ${o.status}/${o.outcome}; ${o.netRMultiple??o.rMultiple} R netto; ${o.netPnlUsd} USD`)]);
const fieldValue=(field,value)=>field.endsWith('_time')||field==='created_at'?date(value):value;
const forex=audit.results.slice(0,2);
const refs=forex[0].references.filter(r=>r.rebuilt);
const checklistRows=id=>runs.flatMap((r,index)=>{const groups=r.groups.filter(g=>g.snapshot.setupKey===`GBPUSD:setup1:${id}`);
  if(!groups.length)return [[index?'Neuaufbau':'Live','Keine DR gespeichert','—','—','—','—','—','Keine Entries']];
  return groups.map(g=>{
  const s=g.firstValidated??g.snapshot,p=s.checklist.setup.primary,c=p.checks;
  return [index?'Neuaufbau':'Live',date(s.knownAt),s.dealingRange.status,pretty(Object.fromEntries(Object.entries(c).map(([k,v])=>[k,v?.status]))),p.invalidation,p.targetSelection?.target1?.price,p.targetSelection?.target2?.price,
    r.entries.filter(e=>e.snapshot.setupKey===s.setupKey).map(e=>date(e.snapshot.entry.recognizedAt)).join('; ')];});});
const colors=await fs.readFile('src/chartColors.js','utf8');const token=name=>colors.match(new RegExp(name+': \\{ hex: "(#[a-fA-F0-9]+)"'))?.[1]??'#aaaaaa';
const m5=await read('local-data/setup1-sets/'+forex[0].setId+'/M5.json');
function diagram(ref){const at=Date.parse(ref.rebuilt.ob_start_time)/1000,cs=m5.filter(c=>c.time>=at-3600&&c.time<=at+1800),levels=[ref.live.fractal_price,ref.rebuilt.fractal_price,ref.live.ls_price,ref.live.ob_top,ref.live.ob_bottom];
  const lo=Math.min(...cs.map(c=>c.low),...levels)-.0001,hi=Math.max(...cs.map(c=>c.high),...levels)+.0001;
  const y=p=>280-(p-lo)/(hi-lo)*235,x=t=>40+(t-(at-3600))/5400*700;
  let svg=cs.map(c=>{const color=token(c.close>=c.open?'candleUp':'candleDown');return `<line x1="${x(c.time)}" x2="${x(c.time)}" y1="${y(c.low)}" y2="${y(c.high)}" stroke="${color}"/><rect x="${x(c.time)-3}" y="${y(Math.max(c.open,c.close))}" width="6" height="${Math.max(1,Math.abs(y(c.open)-y(c.close)))}" fill="${color}"/>`;}).join('');
  for(const [label,price,color] of [['Fraktal Live',ref.live.fractal_price,token('liquiditySweepM5')],['Fraktal Neu',ref.rebuilt.fractal_price,token('liquidityLowM5')],['OB oben',ref.live.ob_top,token('candleDown')],['OB unten',ref.live.ob_bottom,token('obBullM5')]])svg+=`<line x1="40" x2="740" y1="${y(price)}" y2="${y(price)}" stroke="${color}" stroke-dasharray="4 4"/><text x="750" y="${y(price)}" fill="${color}">${label} ${price.toFixed(5)}</text>`;
  return `<svg viewBox="0 0 1030 330" role="img" aria-label="M5-Kerzen und abweichende Fraktalpreise für Setup ${ref.id}">${svg}<text x="40" y="320" fill="#ddd">${escape(date(at-3600))} bis ${escape(date(at+1800))} · FXCM Bid · Europe/Berlin</text></svg>`;
}
const html=`<!doctype html><html lang="de"><meta charset="utf-8"><title>Setup-1-Abgleich und September-Probelauf</title><style>body{font:16px/1.5 system-ui;max-width:1250px;margin:35px auto;padding:0 25px;background:#121722;color:#e1e6f0}table{width:100%;border-collapse:collapse;margin:18px 0}td,th{border-bottom:1px solid #394358;padding:8px;text-align:left;overflow-wrap:anywhere}h1,h2,h3,a{color:#90b7ff}svg{width:100%}code{overflow-wrap:anywhere}</style>
<h1>Setup 1: Herkunft des Überschusses und Septembervergleich</h1><p>Lokaler Branch codex/wave2-setup1-audit auf Welle-1-Stand 6757524. Keine Live-Zeile verändert, nichts veröffentlicht. Alle Uhrzeiten Europe/Berlin.</p>
<h2>Belegter Hauptgrund</h2><p>Der Neuaufbau verwendet die heutige 24-Stunden-Erkennung rückwirkend. Der alte Backfill filtert 07:00–17:45; der Live-Wächter verließ zuvor außerhalb seines gepufferten Alarmfensters den Lauf. Erst Commit 9b6b759 vom 23.09.2026 änderte dies auf ganztägige Erkennung. Die Spread-Hour-Ausblendung folgte mit ac59f73 am 27.09.2026. Git-Zeitpunkte belegen Codeänderungen, keine exakten Deploy-Zeitpunkte.</p>
${table(['Instrument','Neu','Live','Gemeinsam','Nur neu','Nur live','Außerhalb Handel','Außerhalb heutiger Alarme'],forex.map(r=>[r.instrument,r.total,r.live,r.shared,r.only,r.missing,r.outsideTrading,r.outsideAlarm]))}
<p>EURUSD: Die grobe Aufgabenangabe 760 ist im eingefrorenen Satz nicht bestätigt; es sind 665. Außerhalb eines Fensters ist ein Merkmal, kein eigenständiger Kausalbeweis für jede Zeile.</p>
${table(['Gegenprobe','Instrument','Treffer','Entfernte Mehrtreffer','Zurückgewonnene Live-only','Verbleibend zusätzlich'],counter.map(r=>[r.name,r.instrument,r.total,r.removedRebuildOnly,r.recoveredLiveOnly.length,r.additional]))}
<p>Das alte Fenster entfernt 634/643 GBPUSD- und 656/665 EURUSD-Mehrtreffer (98,6 %). Jeweils neun bleiben ungeklärt; sie werden nicht als bewiesene neue Handelssignale bezeichnet. Der Fensterfilter verliert auch gemeinsame Treffer: Er ist kein verlustfreier Ersatz des Live-Bestands. Die isolierte Änderung von M5-Schluss zu Legacy-Zeit verändert keinen Schlüssel.</p>
${forex.map(r=>`<h3>${r.instrument}: Verteilungen und Feldabweichungen</h3>${table(['Kategorie (disjunkt)','Anzahl'],Object.entries(r.categories))}<p>„nearSameLevelsShiftedOb“: gleiche Sweep-/Fraktalpreise, andere OB-Zeit innerhalb einer Stunde; Ähnlichkeit, kein bewiesenes Duplikat. Diese ${r.categories.nearSameLevelsShiftedOb??0} Fälle liegen ebenfalls außerhalb der heutigen Alarme.</p>${table(['Berlin-Stunde','Mehrtreffer'],Object.entries(r.hour).sort())}${table(['Wochentag','Mehrtreffer'],Object.entries(r.weekday))}${table(['Sweep-Anzahl','Mehrtreffer'],Object.entries(r.sweepCount))}${table(['Primär-Sweep','Mehrtreffer'],Object.entries(r.primary))}${table(['Nächster Live-OB (gleiche Richtung)','Mehrtreffer'],Object.entries(r.distance))}<p>${r.changedKeys}/${r.shared} gemeinsame Schlüssel unterscheiden sich fachlich. Zahlen je Feld überlappen; numerische DB-Rundung unter 1e-12, created_at und alert_price sind ausgeklammert.</p>${table(['Feld','Abweichungen'],Object.entries(r.fields))}${table(['Monat','Gemeinsam','Erkennung gleich','Nur live','Nur neu'],Object.entries(r.months).map(([m,c])=>[m,c.sameKey,c.detectionFieldsEqual,c.liveOnly,c.rebuiltOnly]))}`).join('')}
<h2>Nur Live</h2>${table(['Instrument','Spread-Hour-Gegenprobe: zurückgewonnene IDs','Rest offen'],ignore.map(r=>[r.instrument,r.recoveredLiveOnly.join(', '),forex.find(x=>x.instrument===r.instrument).missing-r.recoveredLiveOnly.length-(r.instrument==='GBPUSD'?1:0)]))}
<p>Die Gegenprobe ohne Ignore-Sessions reproduziert acht fehlende GBPUSD- und zehn EURUSD-Schlüssel. Sie verändert weitere Treffer und ist nur ein Ursachenexperiment. GBPUSD 4986: created_at 23.09.2026 22:38:09, OB vom 27.07.2026 14:10, Abstand 58,35 Tage; dies kann nicht aus dem aktuellen Sechs-Stunden-Lookback stammen. Die historischen Tick-, Feed-, Deployment- und Einstellungsstände fehlen. 37 GBPUSD- und 23 EURUSD-Fälle bleiben kausal unaufgelöst. Historisch wurde zudem vor September cTrader verwendet; aktuelle FXCM-Kerzen sind kein identischer damaliger Input.</p>
<h2>Referenzen: 3070, 3125 / DR 97 und 5491 / DR 105</h2>${refs.map(ref=>`<h3>${ref.id}</h3>${table(['Feld','Live','Neuaufbau'],['fractal_price','fractal_pivot_time','ls_price','ls_pivot_time','ls_touched_time','ls_timeframe','ob_top','ob_bottom','ob_start_time','ob_fvg','invalidation','created_at'].map(f=>[f,fieldValue(f,ref.live[f]),fieldValue(f,ref.rebuilt[f])]))}${table(['Quelle','TF','Preis','Pivot Berlin','Touch Berlin','Primär'],[ref.live,ref.rebuilt].flatMap((r,i)=>r.trade_setup_sweeps.map(s=>[i?'Neu':'Live',s.timeframe,s.price,date(s.pivot_time),date(s.touched_time),s.is_primary])))}${diagram(ref)}${table(['Quelle','Validierter Stand','DR-Status','Checkpoints','Invalidation','T1','T2','Entries Berlin'],checklistRows(ref.id))}`).join('')}
<p>3125: Neuaufbau erkennt zuerst am 16.09. 08:10 und friert diesen ersten Treffer ein. Fraktal/Sweep repräsentieren einen anderen historischen Zustand als die Live-Zeile (Fraktal 1,34962 statt 1,34980; Pivot 15.09. 15:55 statt 16.09. 08:00; zusätzlicher M5-Sweep). Welche damalige Feed-/Upsert-/Konfigurationsänderung diesen Zustand verursachte, ist ohne Versionierung nicht beweisbar. 5491: nur Rundung und Erkennungszeit 10:20 statt 10:21:02; keine geänderte Erkennungsgeometrie. Die Tabellen zeigen die tatsächlich daraus entstandenen A–H-/Entry-Stände, keine hypothetische Wirkung.</p>
<h2>September: identische eingefrorene Lauf-Eingaben, unterschiedlicher Setup-Satz</h2>${table(['Quelle','Run-ID','Quell-Setups','DRs','Jemals bestätigt','Validiert','DR-Ausgänge','Entries','Scan Sekunden'],runs.map((r,i)=>[i?'Neuaufbau':'Live',r.metrics.runId,r.metrics.setups,r.metrics.drs,r.metrics.confirmedEver,r.metrics.validated,pretty(r.metrics.outcomes),r.metrics.entries,(r.metrics.wallMs/1000).toFixed(3)]))}
${runs.map((r,i)=>`<h3>${i?'Neuaufbau':'Live'}: Entry-Ergebnisse</h3>${table(['Setup','Entry Berlin','Preis','Weit','Eng'],entryRows(r))}`).join('')}
<p>Der Aufgabenreferenzwert 21 T1 wird gegen den aktuellen Welle-1-Preisbeobachtungsstand geprüft: Dieser trennt ungeklärte Kerzenlücken konservativ von belegten Ausgängen. Eine Differenz der Definitionen ist keine Änderung von Entry-Ausgängen.</p>
<p><strong>Konkreter Entry-Unterschied:</strong> Beide Entries zu 3125 (16.09. 09:34 und 10:25) und beide zu 5491 (24.09. 10:36 und 11:05) bleiben mit identischen Preisen und bytegleichen Outcome-Objekten bestehen. Die beiden fehlenden Entries betreffen 3070 (04.09. 10:09 und 11:52). Dort bleibt die DR validiert, aber der primäre Sweep wechselt von M5/09:30 zu H1/09:00. Entry Pattern 1 sucht den M1-CHoCH-Ursprung genau in den fünf Minuten des primären Sweeps (m1SweepReaction.js). Der ursprüngliche CHoCH-Ursprung 09:33 gehört in das alte Fenster 09:30–09:35, nicht in 09:00–09:05. Damit ist dieser Entry-Beleg im neuen Satz nicht mehr zulässig.</p><p>Belegte T1 vor Invalidation: Live 18, Neuaufbau 20; Invalidation vor T1: 24 bzw. 29; nicht belegt: fünf bzw. acht. Der ursprüngliche Aufgabenwert 21 T1 stammt aus einer anderen Beobachtungsdefinition; als unveränderte Referenz wird hier der fertige Welle-1-Lauf verwendet. Laufzeit Neuaufbau 903,940 Sekunden (15:03,9 Minuten), Live 640,825 Sekunden. Nebenher liefen leichte Audit-Gegenproben, Tests und ein AST-Update; kein zweiter Monats-/Jahreslauf.</p><h2>Empfehlung und Freigaben</h2><p>Für Jahresläufe zunächst den bisherigen Live-Bestand als explizit bezeichnete Referenz beibehalten; der Neuaufbau bleibt Opt-in. Er ist reproduzierbar, aber ein rückwirkender heutiger Detektor auf dem FXCM-Archiv, kein historisches Live-Abbild. Als Nacharbeit historische Fenster-/Regel-/Feed-Versionen modellieren und beide Input-Populationen getrennt vergleichen. Keinen Handelszeitfilter ungeprüft in die Erkennung einbauen: Die Simulation besitzt bereits ihr Handelszeit-Gate, heutige Live-Erkennung arbeitet absichtlich ganztägig.</p><p>Herkunftsfelder und nullable Migration werden separat vorbereitet. Anwendung, Edge-Deploy, Push und Publish benötigen Freigabe. Rohdaten und Gegenproben: local-data/setup1-audit; neuer Lauf: .debug/wave2-rebuild-september. Eingabesätze wurden verlustfrei kopiert; Originale unangetastet.</p></html>`;
await fs.writeFile('docs/setup1-audit-2026.html',html);console.log(runs.map(r=>r.metrics));
